env: FreewayNoFrameskip-v4
load: ""
save: ""
device: ""
demo: False
steps: 5_000_000
seed: 0
eval_interval: 50_000
gamma: 0.99
replay_capacity: 1_000_000
dueling: False
prioritized: False
name: ""
color: False
high_reso: False
no_stack: False
replay_start_step: 50_000
nstep: 1
huber: True
model_evacuation: True
