env: FreewayNoFrameskip-v4
env1: ""
load: ""
load1: ""
task_num: 1
save: ""
device: ""
demo: False
steps: 5_000_000
seed: 0
eval_interval: 50_000
gamma: 0.99
replay_capacity: 1_000_000
dueling: False
prioritized: False
name: ""
color: False
high_reso: False
no_stack: False
replay_start_step: 50_000
nstep: 5
huber: True
model_evacuation: True
net_version: 2
no_grow: True
param_coef: 1e-5
struct_retio: 1
param_retio: 1